# Generated by Django 3.2.8 on 2021-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
            ],
        ),
    ]
