# Generated by Django 3.2.8 on 2021-11-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
