# Generated by Django 3.2.8 on 2021-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todo_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='off_listed',
            field=models.BooleanField(default=False),
        ),
    ]
