# Generated by Django 3.2.8 on 2021-11-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todo_off_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='off_listed',
        ),
    ]
